# Generated by Django 4.0.3 on 2022-04-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='color',
        ),
    ]
