# Generated by Django 4.0.3 on 2022-04-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_subcategory_c_id_remove_product_s_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference_id',
            field=models.IntegerField(default=0),
        ),
    ]
