# Generated by Django 4.0.3 on 2022-04-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_product_reference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=50)),
                ('msg', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
