# Generated by Django 4.0.3 on 2022-04-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_cart_cartitems_delete_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
