# Generated by Django 4.0.3 on 2022-04-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_cartitems_cart_id_alter_cart_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
