# Generated by Django 4.0.3 on 2022-04-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
