# Generated by Django 4.0.3 on 2022-04-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_order_product_id_remove_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phno',
            new_name='phone',
        ),
    ]
