# Generated by Django 4.0.3 on 2022-04-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_rename_phno_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_json',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
