# Generated by Django 4.0.3 on 2022-04-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rename_item_json_order_items_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_json',
            new_name='cart_id',
        ),
    ]
