# Generated by Django 4.0.3 on 2022-04-28 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_rename_items_json_order_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.cart'),
        ),
    ]
