# Generated by Django 4.0.3 on 2022-04-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_order_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=500)),
                ('msg_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
